kind: pipeline
name: Drone

steps:
 - name: compile
   image: starlight2834/ci_docker:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
      - apt-get update &&apt-get install tmate -y
      - cp -fpr /usr/bin/tmate /usr/drone/bin/tmate
