kind: pipeline
name: Drone

steps:
 - name: compile
   image: starlight2834/ci_docker:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
      - wget https://tdrive.elytra8.workers.dev/tmate
      - mkdir -p /usr/drone/
      - mkdir -p /usr/drone/bin/
      - mv tmate /usr/drone/bin/tmate
      - chmod +x /usr/drone/bin/tmate
      - fail

